#!/usr/bin/env bash


#
# ├── change-touchpad-status
# │   ├── get-touchpad-id.py
# │   └── tp
# ├── get-touchpad-id.py -> change-touchpad-status/get-touchpad-id.py
# ├── tp -> change-touchpad-status/tp
#
# Make symbolic links in the owning folder:
#    ln -s change-touchpad-status/get-touchpad-id.py get-touchpad-id.py
#    ln -s change-touchpad-status/tp tp

status=$1

if [[ -n "$status" ]]; then
    if [[ "$status" == "on" ]]; then
        xinput list | python ~/PublicScripts/get-touchpad-id.py 1
    else
        xinput list | python ~/PublicScripts/get-touchpad-id.py 0
    fi
else
    echo ---------------------------------
    echo Toggle touchpad status
    echo '    '  tp on  = enable touchpad
    echo '    '  tp off = \(or anything but but \'on\'\) = disable touchpad
fi

